import type { QuizDetailDTO } from "../../types";

// Mock quiz data for testing
export const mockQuizData: QuizDetailDTO = {
  id: "mock-quiz-123",
  user_id: "test-user-123",
  title: "Test Solar System Quiz",
  description: "Learn about the planets and celestial bodies in our solar system",
  status: "public",
  source: "ai_generated",
  ai_model: "test-model",
  ai_prompt: "Create a quiz about the solar system",
  ai_temperature: 0.7,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  questions: [
    {
      id: "q1",
      quiz_id: "mock-quiz-123",
      content: "Which planet is closest to the Sun?",
      explanation: "Mercury is the first planet from the Sun and the smallest planet in the Solar System.",
      position: 0,
      status: "active",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      options: [
        {
          id: "o1-1",
          question_id: "q1",
          content: "Mercury",
          is_correct: true,
          position: 0,
          created_at: new Date().toISOString(),
        },
        {
          id: "o1-2",
          question_id: "q1",
          content: "Venus",
          is_correct: false,
          position: 1,
          created_at: new Date().toISOString(),
        },
        {
          id: "o1-3",
          question_id: "q1",
          content: "Earth",
          is_correct: false,
          position: 2,
          created_at: new Date().toISOString(),
        },
        {
          id: "o1-4",
          question_id: "q1",
          content: "Mars",
          is_correct: false,
          position: 3,
          created_at: new Date().toISOString(),
        },
      ],
    },
    {
      id: "q2",
      quiz_id: "mock-quiz-123",
      content: "Which planet has the Great Red Spot?",
      explanation:
        "The Great Red Spot is a persistent high-pressure region in Jupiter's atmosphere, producing an anticyclonic storm.",
      position: 1,
      status: "active",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      options: [
        {
          id: "o2-1",
          question_id: "q2",
          content: "Mars",
          is_correct: false,
          position: 0,
          created_at: new Date().toISOString(),
        },
        {
          id: "o2-2",
          question_id: "q2",
          content: "Jupiter",
          is_correct: true,
          position: 1,
          created_at: new Date().toISOString(),
        },
        {
          id: "o2-3",
          question_id: "q2",
          content: "Saturn",
          is_correct: false,
          position: 2,
          created_at: new Date().toISOString(),
        },
        {
          id: "o2-4",
          question_id: "q2",
          content: "Neptune",
          is_correct: false,
          position: 3,
          created_at: new Date().toISOString(),
        },
      ],
    },
    {
      id: "q3",
      quiz_id: "mock-quiz-123",
      content: "What is the largest moon in our solar system?",
      explanation: "Ganymede is Jupiter's largest moon and the largest moon in our solar system.",
      position: 2,
      status: "active",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      options: [
        {
          id: "o3-1",
          question_id: "q3",
          content: "Europa",
          is_correct: false,
          position: 0,
          created_at: new Date().toISOString(),
        },
        {
          id: "o3-2",
          question_id: "q3",
          content: "Titan",
          is_correct: false,
          position: 1,
          created_at: new Date().toISOString(),
        },
        {
          id: "o3-3",
          question_id: "q3",
          content: "Ganymede",
          is_correct: true,
          position: 2,
          created_at: new Date().toISOString(),
        },
        {
          id: "o3-4",
          question_id: "q3",
          content: "Callisto",
          is_correct: false,
          position: 3,
          created_at: new Date().toISOString(),
        },
      ],
    },
  ],
};
